### ISSUE TITLE
Are these defines needed?

### ISSUE THREAD

**Issue by alex-code** [DFRobot/DFRobot_LIS#1]
I've got a SEN0405 I'm trying to use in a project that also uses `AsyncTCP` and there's a conflict with the `ERR_OK` define at https://github.com/DFRobot/DFRobot_LIS/blob/master/src/DFRobot_LIS2DW12.h#L29

Is this needed?

**Comment by pleasetakeup** [comment]
You can remove it without causing errors, it's redundant code
